---
- name: Setup minio
  hosts: all
  become: yes
  tasks:
  - name: Add the minio system group
    group: name=minio state=present
  - name: Add minio user
    user: name=minio group=minio system=yes
  - name: Download latest minio binary
    get_url: url=https://dl.min.io/server/minio/release/linux-amd64/minio dest=/usr/local/bin/minio force=yes mode=0755
  - name: Copy minio service file to systemd directory
    template: src=minio.service.tpl dest=/etc/systemd/system/minio.service owner=root
  - name: Ensure config directory exists
    file: path=/etc/minio owner=root group=root mode=0755 state=directory
  - name: Copy minio config file to the directory
    template: src=minio.conf.tpl dest=/etc/minio/minio.conf owner=root
  - name: Force systemd to reread configs
    systemd: daemon_reload=yes
  - name: Setup minio data directory
    file: path=/srv/minio/data owner=minio group=minio state=directory